### PR TITLE
[fix] Invalid characters (CR/LF) in response header caused by customized Jackson ObjectMapper

### LINKED ISSUE #57: adding multiple triggers causes exception
If you add multiple triggers to a HtmxResponse, like:
```
		htmxResponse.addTrigger("hyperlinkChanged");
		htmxResponse.addTrigger("hideModal");
```
Spring will throw a IllegalArgumentException (Spring boot 3.1).
As it seems a cr/lf is added instead of a coma to separate the different triggers:
```
java.lang.IllegalArgumentException: Invalid characters (CR/LF) in header HX-Trigger
	at org.springframework.util.Assert.isTrue(Assert.java:140) ~[spring-core-6.0.11.jar:6.0.11]
	at org.springframework.security.web.firewall.FirewalledResponse.validateCrlf(FirewalledResponse.java:76) ~[spring-security-web-6.1.2.jar:6.1.2]
	at org.springframework.security.web.firewall.FirewalledResponse.setHeader(FirewalledResponse.java:53) ~[spring-security-web-6.1.2.jar:6.1.2]
	at jakarta.servlet.http.HttpServletResponseWrapper.setHeader(HttpServletResponseWrapper.java:132) ~[tomcat-embed-core-10.1.11.jar:6.0]
	at jakarta.servlet.http.HttpServletResponseWrapper.setHeader(HttpServletResponseWrapper.java:132) ~[tomcat-embed-core-10.1.11.jar:6.0]
	at io.github.wimdeblauwe.hsbt.mvc.HtmxViewHandlerInterceptor.setTriggerHeader(HtmxViewHandlerInterceptor.java:120) ~[htmx-spring-boot-thymeleaf-2.1.0.jar:2.1.0]
	at io.github.wimdeblauwe.hsbt.mvc.HtmxViewHandlerInterceptor.addHxHeaders(HtmxViewHandlerInterceptor.java:85) ~[htmx-spring-boot-thymeleaf-2.1.0.jar:2.1.0]
	at io.github.wimdeblauwe.hsbt.mvc.HtmxViewHandlerInterceptor.postHandle(HtmxViewHandlerInterceptor.java:81) ~[htmx-spring-boot-thymeleaf-2.1.0.jar:2.1.0]
```
edit: i've realised I was one version behind. Just changed the stracktrace.

### PR DESCRIPTION
**Pull request by xhaggi**
Due to the fact that a user can customize the Jackson ObjectMapper bean (e.g. `spring.jackson.serialization.indent-output=true`) in Spring Boot, this leads to unwanted errors when it comes to serializing. Therefore, we no longer rely on this ObjectMapper.

Fixes #57

### CODE REVIEW

File: htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java [hunk 1]
```diff
@@ -26,14 +27,13 @@ public class HtmxMvcAutoConfiguration implements WebMvcRegistrations, WebMvcConf
...
-                             ObjectFactory<LocaleResolver> locales,
-                             ObjectMapper objectMapper) {
+                             ObjectFactory<LocaleResolver> locales) {
         Assert.notNull(resolver, "ViewResolver must not be null!");
         Assert.notNull(locales, "LocaleResolver must not be null!");
 
         this.resolver = resolver;
         this.locales = locales;
-        this.objectMapper = objectMapper;
+        this.objectMapper = JsonMapper.builder().build();
```
Comment (checketts) [inline htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java:36]: `HtmxTrigger` details is an `Object`, however it appears that the HtmxResponse API only supports strings. I was worried that moving to an un-costimizable mapper might limit us someway, but it looks like the `HtmxResponse` API for adding triggers is just strings. So I'm guessing this change is fine.

**Review by checketts — APPROVED** [review]

File: htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java (hunk 1 above)
Comment (wimdeblauwe) [reply htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java:36]: ok, thanks for verifying this. I guess we can merge this?

Comment (checketts) [reply htmx-spring-boot/src/main/java/io/github/wimdeblauwe/htmx/spring/boot/mvc/HtmxMvcAutoConfiguration.java:36]: Yes. Let's merge it please
